### ISSUE TITLE
Call to FAtoGDB failed

### ISSUE THREAD

**Issue by Audald** [thegenemyers/FASTGA#2]
Hi FastGA developers,

The following error is thrown when I run the simple test `FastGA assembly1.fasta assembly2.fasta`:

```
realloc(): invalid next size

FastGA: Call to FAtoGDB failed
```

I can see the file/module FAtoGDB present in the same FASTGA folder after compilation. I wonder if this is a compilation issues from my end (`git clone` + `make`) or an issue of modules not communicating as expected.

Thanks for the release of the tool and for your assistance!

**Comment by thegenemyers** [comment]
Hmmm, I ran exactly this and it was fine on my machine.  The realloc message is from the system, probably size was too big or negatve or ...  Could you send me one or both of the .fasta files?  Alternatively, another user found a small bug that may indeed be exactly the problem -- you could first try grabbing a new copy (I accepted the user's pull request) and see if that
fixes it.  If not, then the .fasta's please so I can debug.  Thanks,  Gene

**Comment by Audald** [comment]
Hi @thegenemyers,

compiling the new copy worked, thanks for the suggestion
